version: '3.8'

services:

  postgres:
    image: postgres:13
    container_name: nestjs_intro.postgres
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nestjs_intro
    networks:
      - nestjs_intro

  test-db:
    image: postgres:13
    container_name: nestjs_intro.test.postgres
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nestjs_intro
    networks:
      - nestjs_intro


networks:
  nestjs_intro:
